spring.application.name=judge-plaform

# Snowflake (0~31)
app.snowflake.worker-id=1
app.snowflake.datacenter-id=1

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/judge_plaform?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false
spring.datasource.username=root
spring.datasource.password=737452105

# MyBatis-Plus
mybatis-plus.mapper-locations=classpath*:mapper/*.xml
mybatis-plus.type-aliases-package=com.aijudge.judgeplaform.pojo.domain
mybatis-plus.configuration.map-underscore-to-camel-case=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=judge-media

# Upload size limit
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
